Vagrant.configure("2") do |config|

    # Define a Vagrant VM for k3s server
    config.vm.define "ysakineS" do |server|
        server.vm.hostname = "ysakineS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.network "forwarded_port", guest: 22, host: 2237, id: "ssh"
        server.vm.box = "ubuntu/bionic64"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end
        server.vm.provision "shell", path: "scripts/install-k3s-server.sh"
    end
end
