Vagrant.configure("2") do |config|

  config.vm.define "ysakineS" do |control|
    config.vm.hostname = "ysakineS"
    config.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"
    config.vm.network "forwarded_port", guest: 22, host: 1337, id: "ssh"
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      # install k3s
      curl -sfL https://get.k3s.io | sh -
      # allow k3s traffic
      # ufw allow 6443/tcp
      # ufw allow 8472/udp
      # ufw allow 10250/tcp
      # ufw --force enable
    SHELL

  end

  # config.vm.define "ysakineSW" do |control|
  #   config.vm.hostname = "ysakineSW"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
