Vagrant.configure("2") do |config|


  # Define a Vagrant VM for k3s server
  config.vm.define "ysakineS" do |server|
    server.vm.hostname = "ysakineS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 22, host: 1337, id: "ssh"
    server.vm.box = "ubuntu/bionic64"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install-k3s-server.sh"
  end

  #Define a Vagrant VM for k3s worker
  config.vm.define "ysakineSW" do |worker|
    worker.vm.hostname = "ysakineSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.network "forwarded_port", guest: 22, host: 1338, id: "ssh"
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/install-k3s-agent.sh"
  end
end
